### ISSUE TITLE
有个BUG

### ISSUE THREAD

**Issue by Moxyu** [Slowlyo/owl-operation-log#1]
![image](https://github.com/slowlyo/owl-operation-log/assets/49427582/31243552-ce28-446b-863c-59889d817a76)

allowed_methods在数据库中是以字符串存储并且用逗号分割

setting实际上获取到的是一个字符串，然后转换为Array，就变成了一个单元素的数组

![image](https://github.com/slowlyo/owl-operation-log/assets/49427582/54b73b4e-1aa4-40dc-be67-dd276a58358d)

然后匹配请求方法的时候，无论如何都匹配不成功。

导致记录不上对应请求方法的日志。

**Comment by slowlyo** [comment]
直接提pr吧    这扩展太久没看了

**Comment by Moxyu** [comment]
补充扩展设置页面

![image](https://github.com/slowlyo/owl-operation-log/assets/49427582/60bd0a21-aae4-4e71-afe2-92b8628c6fd0)

**Comment by Moxyu** [comment]
> 直接提pr吧 这扩展太久没看了

ok
